# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\JasmineJones\Documents\Start\mathGood.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
import time
from random import uniform
from PyQt5.QtWidgets import QApplication, QMainWindow, QAbstractScrollArea, QWidget

class Ui_MathWindow(object):

    def equa(self):
        self.x = int(uniform(1,15))
        self.y = int(uniform(1,4))
        self.z = int(uniform(1,15))
        self.equation.setText(str(self.x)+"  "+self.op(self.y)+"  "+str(self.z))

    def op(self,y):
        match y:
            case 1:
                y = '+'
            case 2:
                y = '-'
            case 3:
                y = '*'
            case 4:
                y = '/'

        return y  

    def submit_btn(self):

        match self.op(self.y):
            case '+':
                ans = self.x + self.z
            case '-':
                ans = self.x - self.z
            case '*':
                ans = self.x * self.z
            case '/':
                ans = self.x / self.z

        if ans == self.answer.text():
            self.count=self.count+1
            self.incorrect.setText(str(self.count)+" Correct")
            self.attempts = 0
            self.equa()
        else:
            self.attempts = self.attempts+1
            match self.attempts:
                case 1:
                    self.incorrect.setText("Incorrect... try again"+str(self.attempts))
                case 2:
                    self.incorrect.setText("hmm... try again"+str(self.attempts))
                case 3:
                    self.incorrect.setText("Lets try something else"+str(self.attempts))
                    self.equa()
                    self.attempts = 0

    def quit_btn(self):
        QApplication.closeAllWindows()
        self.StartWindow = QMainWindow()
        #self.ui = Ui_Start()
        self.ui.setupUi(self.StartWindow)
        self.StartWindow.show()

    def setupUi(self, MathWindow):
        MathWindow.setObjectName("MathWindow")
        MathWindow.resize(571, 419)
        self.centralwidget = QtWidgets.QWidget(MathWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")


        self.whatIs = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.whatIs.setFont(font)
        self.whatIs.setAlignment(QtCore.Qt.AlignCenter)
        self.whatIs.setObjectName("whatIs")
        self.verticalLayout.addWidget(self.whatIs)


        self.equation = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.equation.setFont(font)
        self.equation.setAlignment(QtCore.Qt.AlignCenter)
        self.equation.setObjectName("equation")
        self.verticalLayout.addWidget(self.equation)


        self.answer = QtWidgets.QLineEdit(self.centralwidget)
        self.answer.setAlignment(QtCore.Qt.AlignCenter)
        self.answer.setObjectName("answer")
        self.verticalLayout.addWidget(self.answer)


        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setEnabled(True)
        self.submit.setMaximumSize(QtCore.QSize(100, 50))
        self.submit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.submit.setObjectName("submit")
        self.horizontalLayout.addWidget(self.submit)
        self.submit.clicked.connect(self.submit_btn)

        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setEnabled(True)
        self.quit.setMaximumSize(QtCore.QSize(100, 50))
        self.quit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.quit.setObjectName("quit")
        self.horizontalLayout.addWidget(self.quit)
        self.quit.clicked.connect(self.quit_btn)

        self.verticalLayout.addLayout(self.horizontalLayout)


        self.incorrect = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.incorrect.setFont(font)
        self.incorrect.setAlignment(QtCore.Qt.AlignCenter)
        self.incorrect.setObjectName("incorrect")
        self.verticalLayout.addWidget(self.incorrect)


        MathWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MathWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 21))
        self.menubar.setObjectName("menubar")
        MathWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MathWindow)
        self.statusbar.setObjectName("statusbar")
        MathWindow.setStatusBar(self.statusbar)

        self.count = 0
        self.attempts = 0
        self.x = int(uniform(1,15))
        self.y = int(uniform(1,4))
        self.z = int(uniform(1,15))

        self.retranslateUi(MathWindow)
        QtCore.QMetaObject.connectSlotsByName(MathWindow)

    def retranslateUi(self, MathWindow):
        _translate = QtCore.QCoreApplication.translate
        MathWindow.setWindowTitle(_translate("MathWindow", "MathWindow"))
        self.whatIs.setText(_translate("MathWindow", "What is..."))
        self.equation.setText(_translate("MathWindow", str(self.x)+"  "+self.op(self.y)+"  "+str(self.z)))
        self.submit.setText(_translate("MathWindow", "Submit"))
        self.quit.setText(_translate("MathWindow", "Quit"))
        

if __name__ == "__main__": #### Creates Scene ####
    import sys
    app = QApplication(sys.argv)
    ui = Ui_MathWindow()
    win = QMainWindow()
    ui.setupUi(win)
    win.show()
    sys.exit(app.exec())